FROM python:latest

RUN pip install --no-cache-dir \
    python-dotenv \
    dbt-core \
    dbt-oracle

# RUN apt-get update && \
#     apt-get install -y libpq-dev zlib1g-dev build-essential shared-mime-info libaio1 libaio-dev unzip wget --no-install-recommends && \
#     wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sdk-linux.x64-21.4.0.0.0dbru.zip && \
#     wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip && \
#     wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip && \
#     mkdir -p /opt/oracle && \
#     cp instantclient-* /opt/oracle/ && \
#     cd /opt/oracle/ && \
#     unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip && \
#     unzip instantclient-sdk-linux.x64-21.4.0.0.0dbru.zip && \
#     unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip && \
#     rm -rf /var/lib/apt/lists/* instantclient-basic-linux.x64-21.4.0.0.0dbru.zip instantclient-sdk-linux.x64-21.4.0.0.0dbru.zip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip && \
#     apt -y clean && \
#     apt -y remove wget unzip && \
#     apt -y autoremove && \
#     rm -rf /var/cache/apt

# ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4
ENV DBT_PROJECT_DIR /dbt/hcvn_dbt
ENV DBT_PROFILES_DIR /dbt
ENV ORA_PYTHON_DRIVER_TYPE thin

COPY .. $DBT_PROFILES_DIR
WORKDIR $DBT_PROJECT_DIR

RUN dbt clean
RUN dbt deps