with 
src__tiktok_ad_raw as (select * from {{ source('AP_PRODUCT','AIRBYTE_RAW_TIKTOK_ADS_REPORTS_DAILY') }}),

final as (
select  
    json_value("_AIRBYTE_DATA", '$."ad_id"') as ad_id,
    json_value("_AIRBYTE_DATA", '$."stat_time_day"') as stat_time_day,
    json_value("_AIRBYTE_DATA", '$."metrics"."placement_type"') as placement_type,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_cost_per_conversion"') as real_time_cost_per_conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."dpa_target_audience_type"') as dpa_target_audience_type,
    json_value("_AIRBYTE_DATA", '$."metrics"."reach"') as reach,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_views_p25"') as video_views_p25,
    json_value("_AIRBYTE_DATA", '$."metrics"."app_install"') as app_install,
    json_value("_AIRBYTE_DATA", '$."metrics"."secondary_goal_result"') as secondary_goal_result,
    json_value("_AIRBYTE_DATA", '$."metrics"."frequency"') as frequency,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_views_p100"') as video_views_p100,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_result"') as real_time_result,
    json_value("_AIRBYTE_DATA", '$."metrics"."cpc"') as cpc,
    json_value("_AIRBYTE_DATA", '$."metrics"."ad_text"') as ad_text,
    json_value("_AIRBYTE_DATA", '$."metrics"."campaign_id"') as campaign_id,
    json_value("_AIRBYTE_DATA", '$."metrics"."likes"') as likes,
    json_value("_AIRBYTE_DATA", '$."metrics"."ctr"') as ctr,
    json_value("_AIRBYTE_DATA", '$."metrics"."cpm"') as cpm,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_app_install_cost"') as real_time_app_install_cost,
    json_value("_AIRBYTE_DATA", '$."metrics"."promotion_type"') as promotion_type,
    json_value("_AIRBYTE_DATA", '$."metrics"."total_onsite_shopping_value"') as total_onsite_shopping_value,
    json_value("_AIRBYTE_DATA", '$."metrics"."cta_purchase"') as cta_purchase,
    json_value("_AIRBYTE_DATA", '$."metrics"."follows"') as follows,
    json_value("_AIRBYTE_DATA", '$."metrics"."clicks_on_music_disc"') as clicks_on_music_disc,
    json_value("_AIRBYTE_DATA", '$."metrics"."total_purchase_value"') as total_purchase_value,
    json_value("_AIRBYTE_DATA", '$."metrics"."tt_app_name"') as tt_app_name,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_views_p75"') as video_views_p75,
    json_value("_AIRBYTE_DATA", '$."metrics"."mobile_app_id"') as mobile_app_id,
    json_value("_AIRBYTE_DATA", '$."metrics"."cost_per_1000_reached"') as cost_per_1000_reached,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_cost_per_result"') as real_time_cost_per_result,
    json_value("_AIRBYTE_DATA", '$."metrics"."value_per_complete_payment"') as value_per_complete_payment,
    json_value("_AIRBYTE_DATA", '$."metrics"."result_rate"') as result_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."secondary_goal_result_rate"') as secondary_goal_result_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_app_install"') as real_time_app_install,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_watched_2s"') as video_watched_2s,
    json_value("_AIRBYTE_DATA", '$."metrics"."adgroup_name"') as adgroup_name,
    json_value("_AIRBYTE_DATA", '$."metrics"."cta_conversion"') as cta_conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_watched_6s"') as video_watched_6s,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_conversion_rate"') as real_time_conversion_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."average_video_play"') as average_video_play,
    json_value("_AIRBYTE_DATA", '$."metrics"."onsite_shopping"') as onsite_shopping,
    json_value("_AIRBYTE_DATA", '$."metrics"."adgroup_id"') as adgroup_id,
    json_value("_AIRBYTE_DATA", '$."metrics"."average_video_play_per_user"') as average_video_play_per_user,
    json_value("_AIRBYTE_DATA", '$."metrics"."tt_app_id"') as tt_app_id,
    json_value("_AIRBYTE_DATA", '$."metrics"."result"') as result,
    json_value("_AIRBYTE_DATA", '$."metrics"."shares"') as shares,
    json_value("_AIRBYTE_DATA", '$."metrics"."campaign_name"') as campaign_name,
    json_value("_AIRBYTE_DATA", '$."metrics"."cost_per_result"') as cost_per_result,
    json_value("_AIRBYTE_DATA", '$."metrics"."total_complete_payment_rate"') as total_complete_payment_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."spend"') as spend,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_play_actions"') as video_play_actions,
    json_value("_AIRBYTE_DATA", '$."metrics"."conversion_rate"') as conversion_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."conversion"') as conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."cost_per_conversion"') as cost_per_conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_conversion"') as real_time_conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."video_views_p50"') as video_views_p50,
    json_value("_AIRBYTE_DATA", '$."metrics"."comments"') as comments,
    json_value("_AIRBYTE_DATA", '$."metrics"."vta_conversion"') as vta_conversion,
    json_value("_AIRBYTE_DATA", '$."metrics"."ad_name"') as ad_name,
    json_value("_AIRBYTE_DATA", '$."metrics"."real_time_result_rate"') as real_time_result_rate,
    json_value("_AIRBYTE_DATA", '$."metrics"."impressions"') as impressions,
    json_value("_AIRBYTE_DATA", '$."metrics"."complete_payment"') as complete_payment,
    json_value("_AIRBYTE_DATA", '$."metrics"."total_pageview"') as total_pageview,
    json_value("_AIRBYTE_DATA", '$."metrics"."cost_per_secondary_goal_result"') as cost_per_secondary_goal_result,
    json_value("_AIRBYTE_DATA", '$."metrics"."vta_purchase"') as vta_purchase,
    json_value("_AIRBYTE_DATA", '$."metrics"."clicks"') as clicks,
    json_value("_AIRBYTE_DATA", '$."metrics"."profile_visits"') as profile_visits
from src__tiktok_ad_raw
)

select * from final
