with 
src__appsflyer_inapps as (select * from {{ source('AP_PRODUCT','AIRBYTE_RAW_APPSFLYER_INAPPS') }}),
final as (
select  
    json_value("_AIRBYTE_DATA",'$."utm_medium"') as utm_medium,
    json_value("_AIRBYTE_DATA",'$."campaign_type"') as campaign_type,
    json_value("_AIRBYTE_DATA",'$."_ab_source_file_url"') as ab_source_file_url,
    json_value("_AIRBYTE_DATA",'$."dt"') as dt,
    json_value("_AIRBYTE_DATA",'$."media_type"') as media_type,
    json_value("_AIRBYTE_DATA",'$."appsflyer_id"') as appsflyer_id,
    json_value("_AIRBYTE_DATA",'$."idfv"') as idfv,
    json_value("_AIRBYTE_DATA",'$."fraud_reason"') as fraud_reason,
    json_value("_AIRBYTE_DATA",'$."app_id"') as app_id,
    json_value("_AIRBYTE_DATA",'$."is_primary_attribution"') as is_primary_attribution,
    to_timestamp(json_value("_AIRBYTE_DATA",'$."install_time"'),'YYYY-MM-DD HH24:MI:SS') + interval '7' hour as install_time,
    json_value("_AIRBYTE_DATA",'$."media_source"') as media_source,
    json_value("_AIRBYTE_DATA",'$."utm_campaign"') as utm_campaign,
    json_value("_AIRBYTE_DATA",'$."blocked_sub_reason"') as blocked_sub_reason,
    json_value("_AIRBYTE_DATA",'$."idfa"') as idfa,
    json_value("_AIRBYTE_DATA",'$."advertising_id"') as advertising_id,
    json_value("_AIRBYTE_DATA",'$."af_ad_id"') as af_ad_id,
    json_value("_AIRBYTE_DATA",'$."af_reengagement_window"') as af_reengagement_window,
    json_value("_AIRBYTE_DATA",'$."event_name"') as event_name,
    json_value("_AIRBYTE_DATA",'$."campaign"') as campaign,
    json_value("_AIRBYTE_DATA",'$."is_retargeting"') as is_retargeting,
    json_value("_AIRBYTE_DATA",'$."utm_source"') as utm_source,
    json_value("_AIRBYTE_DATA",'$."blocked_reason_rule"') as blocked_reason_rule,
    json_value("_AIRBYTE_DATA",'$."af_adset_id"') as af_adset_id,
    json_value("_AIRBYTE_DATA",'$."af_ad_type"') as af_ad_type,
    json_value("_AIRBYTE_DATA",'$."retargeting_conversion_type"') as retargeting_conversion_type,
    json_value("_AIRBYTE_DATA",'$."af_prt"') as af_prt,
    json_value("_AIRBYTE_DATA",'$."platform"') as platform,
    json_value("_AIRBYTE_DATA",'$."af_attribution_lookback"') as af_attribution_lookback,
    json_value("_AIRBYTE_DATA",'$."rejected_reason"') as rejected_reason,
    json_value("_AIRBYTE_DATA",'$."af_channel"') as af_channel,
    json_value("_AIRBYTE_DATA",'$."validation_reason_value"') as validation_reason_value,
    json_value("_AIRBYTE_DATA",'$."utm_content"') as utm_content,
    json_value("_AIRBYTE_DATA",'$."af_c_id"') as af_c_id,
    json_value("_AIRBYTE_DATA",'$."h"') as h,
    json_value("_AIRBYTE_DATA",'$."_ab_source_file_last_modified"') as ab_source_file_last_modified,
    json_value("_AIRBYTE_DATA",'$."af_sub1"') as af_sub1,
    json_value("_AIRBYTE_DATA",'$."utm_term"') as utm_term,
    json_value("_AIRBYTE_DATA",'$."utm_id"') as utm_id,
    json_value("_AIRBYTE_DATA",'$."fraud_sub_reason"') as fraud_sub_reason,
    json_value("_AIRBYTE_DATA",'$."is_organic"') as is_organic,
    json_value("_AIRBYTE_DATA",'$."t"') as t,
    json_value("_AIRBYTE_DATA",'$."af_adset"') as af_adset,
    REGEXP_SUBSTR(
        JSON_VALUE("_AIRBYTE_DATA", '$."original_url"'),
        'clickid=([^&]*)',
        1,
        1,
        NULL,
        1
    ) AS click_id,
    json_value("_AIRBYTE_DATA",'$."blocked_reason"') as blocked_reason,
    json_value("_AIRBYTE_DATA",'$."media_channel"') as media_channel,
    json_value("_AIRBYTE_DATA",'$."conversion_type"') as conversion_type,
    json_value("_AIRBYTE_DATA",'$."af_ad"') as af_ad,
    json_value("_AIRBYTE_DATA",'$."customer_user_id"') as customer_user_id,
    json_value("_AIRBYTE_DATA",'$."blocked_reason_value"') as blocked_reason_value,
    to_timestamp(json_value("_AIRBYTE_DATA",'$."event_time"'),'YYYY-MM-DD HH24:MI:SS') + interval '7' hour as event_time
from src__appsflyer_inapps
)

select * from final